[targets]
# name = host or ip
local = 127.0.0.1
web01 = 10.10.10.11

[environments]
# name = comma-separated targets
prod = web01
lab = local

[defaults]
# ssh_user = admin
# ssh_key = ~/.ssh/id_rsa
# winrm_user = Administrator
# winrm_password = ChangeMe